### ISSUE TITLE
Selecting a ball for the boss doesnt work

### ISSUE THREAD

**Issue by nitelystar** [MoOfficial0000/BossPackageBD#2]
I am currently running version 2.12 for my bot right now, everything is working but selecting a ball will not work, this error is showing up
![image](https://github.com/user-attachments/assets/8f2a0db3-b142-4fe8-9623-fe8fd8675b0f)

If you can help, please do

**Comment by MoOfficial0000** [comment]
Hi sorry for the late reply, but I will be working on a fix.

**Comment by MoOfficial0000** [comment]
Hi it has been fixed.
Thanks.
